In [2]:
import pandas as pd 
import numpy as ny

In [5]:
data=pd.read_csv("Cars Datasets 2025.csv",encoding='cp1252')
print(data)

     Company Names         Cars Names                             Engines  \
0          FERRARI      SF90 STRADALE                                  V8
1      ROLLS ROYCE            PHANTOM                                 V12
2             Ford                KA+                         1.2L Petrol
3         MERCEDES            GT 63 S                                  V8
4             AUDI         AUDI R8 Gt                                 V10
...            ...                ...                                 ...
1213        Toyota       Crown Signia                      2.5L Hybrid I4
1214        Toyota  4Runner (6th Gen)  2.4L Turbo I4 (i-FORCE MAX Hybrid)
1215        Toyota      Corolla Cross              2.0L Gas / 2.0L Hybrid
1216        Toyota             C-HR+                   1.8L / 2.0L Hybrid
1217        Toyota     RAV4 (6th Gen)        2.5L Hybrid / Plug-in Hybrid

        CC/Battery Capacity    HorsePower Total Speed  \
0                   3990 cc        963 hp    340 km/h
1                   6749 cc        563 hp    250 km/h
2                  1,200 cc      70-85 hp    165 km/h
3                  3,982 cc        630 hp    250 km/h
4                  5,204 cc        602 hp    320 km/h
...                     ...           ...         ...
1213                2487 cc        240 hp    180 km/h
1214      2393 cc + Battery        326 hp    180 km/h
1215  1987 cc / Hybrid batt  169 – 196 hp    190 km/h
1216  1798 / 1987 cc + batt  140 – 198 hp    180 km/h
1217         2487 cc + batt  219 – 302 hp    200 km/h

     Performance(0 - 100 )KM/H        Cars Prices               Fuel Types  \
0                      2.5 sec        $1,100,000           plug in hyrbrid
1                      5.3 sec          $460,000                    Petrol
2                     10.5 sec    $12,000-$15,000                   Petrol
3                      3.2 sec          $161,000                    Petrol
4                      3.6 sec          $253,290                    Petrol
...                        ...                ...                      ...
1213                   7.6 sec  $43,590 – $48,000  Hybrid (Gas + Electric)
1214                   6.8 sec           $50,000                    Hybrid
1215             8.0 – 9.2 sec  $25,210 – $29,135             Gas / Hybrid
1216            7.9 – 10.5 sec           € 33,000                   Hybrid
1217             6.0 – 8.1 sec  $29,000 – $43,000         Hybrid / Plug-in

     Seats        Torque
0        2        800 Nm
1        5        900 Nm
2        5  100 - 140 Nm
3        4        900 Nm
4        2        560 Nm
...    ...           ...
1213     5        239 Nm
1214     7        630 Nm
1215     5  190 – 210 Nm
1216     5  190 – 205 Nm
1217     5  221 – 400 Nm

[1218 rows x 11 columns]

In [9]:
columns_to_clean=[
    'CC/Battery Capacity',
    'HorsePower',
    'Total Speed',
    'Performance(0-100) KM/H',
    'Cars Price',
    'Torque'

]
def extract_numeric(value):
    """Extracts numbers from a string and returns them as a float or int."""
    if pd.isna(value):
        return np.nan
    
    # Find numbers (including decimals)
    numbers = re.findall(r'[-+]?\d*\.\d+|\d+', str(value))
    if numbers:
        # Check if it has a decimal point
        return float(numbers[0]) if '.' in numbers[0] else int(numbers[0])
    return np.nan


new_column_names = {
    'CC/Battery Capacity': 'Battery Capacity (kWh)',
    'HorsePower': 'HorsePower (HP)',
    'Total Speed': 'Total Speed (km/h)',
    'Performance(0 - 100 )KM/H': '0-100 km/h (seconds)',
    'Cars Prices': 'Price (USD)',
    'Seats': 'Number of Seats',
    'Torque': 'Torque (Nm)'
}

data.rename(columns=new_column_names, inplace=True)

# Show results
print("Cleaned columns:")
print(data[list(new_column_names.values())].head())
print("\n" + "="*60)
print("Data types after cleaning:")
print(data[list(new_column_names.values())].dtypes)

Cleaned columns:
  Battery Capacity (kWh) HorsePower (HP) Total Speed (km/h)  \
0                3990 cc          963 hp           340 km/h
1                6749 cc          563 hp           250 km/h
2               1,200 cc        70-85 hp           165 km/h
3               3,982 cc          630 hp           250 km/h
4               5,204 cc          602 hp           320 km/h

  0-100 km/h (seconds)      Price (USD) Number of Seats   Torque (Nm)
0              2.5 sec      $1,100,000                2        800 Nm
1              5.3 sec        $460,000                5        900 Nm
2             10.5 sec  $12,000-$15,000               5  100 - 140 Nm
3              3.2 sec        $161,000                4        900 Nm
4              3.6 sec        $253,290                2        560 Nm

============================================================
Data types after cleaning:
Battery Capacity (kWh)    object
HorsePower (HP)           object
Total Speed (km/h)        object
0-100 km/h (seconds)      object
Price (USD)               object
Number of Seats           object
Torque (Nm)               object
dtype: object

In [18]:
data.describe()

,Company Names,Cars Names,Engines,Battery Capacity (kWh),HorsePower (HP),Total Speed (km/h),0-100 km/h (seconds),Price (USD),Fuel Types,Number of Seats,Torque (Nm)
count,1218,1218,1218,1215,1218,1218,1212,1218,1218,1218,1217
unique,37,1201,356,311,456,114,180,535,23,19,263
top,Nissan,Polo BlueMotion,I4,1984 cc,355 hp,250 km/h,6.5 sec,"$35,000",Petrol,5,400 Nm
freq,149,2,64,31,23,145,45,36,871,692,72

In [13]:
data.head()

,Company Names,Cars Names,Engines,Battery Capacity (kWh),HorsePower (HP),Total Speed (km/h),0-100 km/h (seconds),Price (USD),Fuel Types,Number of Seats,Torque (Nm)
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Company Names           1218 non-null   object
 1   Cars Names              1218 non-null   object
 2   Engines                 1218 non-null   object
 3   Battery Capacity (kWh)  1215 non-null   object
 4   HorsePower (HP)         1218 non-null   object
 5   Total Speed (km/h)      1218 non-null   object
 6   0-100 km/h (seconds)    1212 non-null   object
 7   Price (USD)             1218 non-null   object
 8   Fuel Types              1218 non-null   object
 9   Number of Seats         1218 non-null   object
 10  Torque (Nm)             1217 non-null   object
dtypes: object(11)
memory usage: 104.8+ KB